# Generated by Django 3.0.8 on 2020-09-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pic',
            field=models.URLField(default='https://i.imgur.com/EqUd38p.png'),
        ),
    ]
