# Generated by Django 3.0.8 on 2020-09-21 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='owner',
            field=models.ForeignKey(default='viviannevilar', on_delete=django.db.models.deletion.CASCADE, related_name='owner_favourites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourite',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects_favourites', to='projects.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_pledges', to='projects.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='supporter',
            field=models.ForeignKey(default='viviannevilar', on_delete=django.db.models.deletion.CASCADE, related_name='supporter_pledges', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='favouriters',
            field=models.ManyToManyField(related_name='favouriter_projects', through='projects.Favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default='viviannevilar', on_delete=django.db.models.deletion.CASCADE, related_name='owner_projects', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('owner', 'project')},
        ),
    ]
