# Generated by Django 3.0.8 on 2020-08-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200826_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_open',
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
