# Generated by Django 3.0.8 on 2020-09-01 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favourites',
            field=models.ManyToManyField(related_name='project_favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
