# Generated by Django 3.0.8 on 2020-09-01 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_auto_20200901_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='favourites',
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_favourites', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_favourites', to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='favouriters',
            field=models.ManyToManyField(related_name='favouriter_projects', through='projects.Favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
