# Generated by Django 3.0.8 on 2020-09-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200901_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='date',
            new_name='date_added',
        ),
    ]
